# Do not modify this file directly! It was generated by ‘nixos-generate-config’.
# Instead, make persistent changes in /etc/nixos/configuration.nix.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  ##############################################
  # Boot & Kernel Configuration
  ##############################################

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  ##############################################
  # Filesystems
  ##############################################

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6379ee57-5917-4b89-bc26-67686b061b2b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A117-35D6";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  ##############################################
  # Platform & Firmware
  ##############################################

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  ##############################################
  # Graphics & NVIDIA Configuration
  ##############################################

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    prime = {
      offload.enable = true;
      offload.enableOffloadCmd = true;
      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };
    powerManagement.enable = false;
    open = false; # Use proprietary driver
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vpl-gpu-rt
    ];
  };

  services.switcherooControl.enable = true;

  ##############################################
  # Power Management
  ##############################################

  services.power-profiles-daemon.enable = false;
  services.auto-cpufreq.enable = true;
  powerManagement.powertop.enable = true;
  services.thermald.enable = lib.mkDefault true;

  ##############################################
  # Networking
  ##############################################

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
}
